### ISSUE TITLE
Issue with Serilog's RequestLogging

### ISSUE THREAD

**Issue by CleytonGoncalves** [khellang/Middleware#104]
Continuing the discussion of #99 .

> Is there any better way?

I don't think so. As I explained in #94, the solution is to re-throw. I would really like to get to the bottom of why your responses turn out empty. Maybe you can turn on debug logging and file a new issue with some more information? 🤔

_Originally posted by @khellang in https://github.com/khellang/Middleware/issues/99#issuecomment-634446307_

Using `options.Rethrow<Exception>()`, a Internal Server Error seems to happen after ProblemDetail's Middleware:

![image](https://user-images.githubusercontent.com/11809167/83041219-3f49aa00-a00e-11ea-9a55-d74f9d9e1c06.png)

![image](https://user-images.githubusercontent.com/11809167/83041148-26d98f80-a00e-11ea-8622-e1f3b0276473.png)

- ProblemDetail gets written as a result
- Serilog's exception log (logged properly AS an exception, the way we wanted it to in the previous thread)
- ASP.NET Core unhandled exception (repeating the exception above)
- HTTP/2 stream error "INTERNAL_ERROR"

```json
{
    "@t": "2020-05-27T11:17:36.1834501-04:00",
    "@mt": "Trace id \"{TraceIdentifier}\": HTTP/2 stream error \"{error}\". A Reset is being sent to the stream.",
    "@m": "Trace id \"0HM029KJ34K0A:0000000F\": HTTP/2 stream error \"INTERNAL_ERROR\". A Reset is being sent to the stream.",
    "@i": "27caf570",
    "@l": "Debug",
    "@x": "Microsoft.AspNetCore.Connections.ConnectionAbortedException: An error occurred after the response headers were sent, a reset is being sent.",
    "TraceIdentifier": "0HM029KJ34K0A:0000000F",
    "error": "INTERNAL_ERROR",
    "EventId": {
        "Id": 35,
        "Name": "Http2StreamResetAbort"
    },
    "SourceContext": "Microsoft.AspNetCore.Server.Kestrel",
    "RequestId": "0HM029KJ34K0A:0000000F",
    "RequestPath": "/meta/Error/500",
    "SpanId": "|9cf60dd2-49f8f7be9198d8e9.",
    "TraceId": "9cf60dd2-49f8f7be9198d8e9",
    "ParentId": "",
    "ThreadId": 91,
}
```

**Comment by khellang** [comment]
Hmm... I'm having trouble seeing where thing go wrong here. It looks like it's encountering an error while actually writing the ProblemDetails to the body stream, is that right?

**Comment by ins0mniaque** [comment]
I had the same problem with my exception handling middleware when rethrowing errors and the fix was to flush the response before rethrowing the exception using `await HttpContext.Response.CompleteAsync ( );`

**Comment by khellang** [comment]
Thanks for that @ins0mniaque! I tried adding a call to `CompleteAsync` after writing the problem details. Pushed [v5.1.1](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/5.1.1) to NuGet. @CleytonGoncalves feel free to reopen this if it doesn't fix your issue 😅

**Comment by ismaelbl** [comment]
Hi, I have the configuration below and I'm also using `options.Rethrow<Exception>()`. The thing it's that I'm still having the same problem described by the op. I'm using v6.5.1.

```
options.UseSerilogRequestLogging(options =>
                {
                    options.MessageTemplate = "Estado: {CodigoEstado}";
                    options.GetLevel = (httpContext, elapsed, ex) =>
                    {
                        if (httpContext.Response.StatusCode > 499)
                            return LogEventLevel.Error;
                        return LogEventLevel.Information;
                    };

                    options.EnrichDiagnosticContext = Enrichers.PushSerilogProperties;
                });
                options.UseProblemDetails();
                options.UseCors(x => x
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader());

                options.UseRouting();
                options.UseAuthenticationWithOptions(null);
                options.UseEndpoints(endpoints => { endpoints.MapControllers(); });
                options.UseSwaggerWithOptions(apiVersionDescriptionProvider, Configuration);

                options.UseDefaultFiles();
                options.UseStaticFiles();
```

That's my logging file after forcing an exception:

```
NT|WEBAP|Aplicación|Anónimo|2023-01-23 14:49:30|Estado: 500|System.ArgumentException: patata
   at ClasesSenFume.Api.Controllers.CentrosController.GetAll(CentroFilterViewModel filter) in C:\Users\ismaelbl\Desktop\Proyectos\ClasesSenFume\sw-csf\src\ClasesSenFume.Api\Controllers\CentrosController.cs:line 48
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)

NT|WEBAP|Aplicación||2023-01-23 14:49:31|Connection id "0HMNT927JN9V4", Request id "0HMNT927JN9V4:00000009": An unhandled exception was thrown by the application.|System.ArgumentException: patata
   at ClasesSenFume.Api.Controllers.CentrosController.GetAll(CentroFilterViewModel filter) in C:\Users\ismaelbl\Desktop\Proyectos\ClasesSenFume\sw-csf\src\ClasesSenFume.Api\Controllers\CentrosController.cs:line 48
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by khellang** [comment]
Hey @ismaelbl! 👋

I don't see any `Rethrow` in the code provided, so I'm not sure how the exception could even reach the logging middleware. Would you mind filing a new issue with more details?
