### ISSUE TITLE
Inner Exception in middleware 

### ISSUE THREAD

**Issue by kinimatt** [khellang/Middleware#49]
I'm getting following error when I use Problem Detail Middleware.

`Error: "An exception was thrown attempting to execute the problem details middleware."
System.ArgumentException: The stream must support writing.
Parameter name: stream
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter..ctor(Stream stream, Encoding encoding, Int32 bufferSize, ArrayPool`1 bytePool, ArrayPool`1 charPool)
   at Microsoft.AspNetCore.Mvc.Internal.MemoryPoolHttpResponseStreamWriterFactory.CreateWriter(Stream stream, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context) in D:\Samples\Middleware\src\ProblemDetails\ProblemDetailsMiddleware.cs:line 88`

**Comment by kinimatt** [comment]
Changing order in Statrtup Configure function solved it. :)
