### ISSUE TITLE
ProblemDetails Xml Response not supported

### ISSUE THREAD

**Issue by NickTholin** [khellang/Middleware#66]
I'm getting an InvalidOperationException when attempting to return a ProblemDetail as text/xml response.

> 2019-09-04 20:58:40.6396|WARN|Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter|An error occurred while trying to create an XmlSerializer for the type 'Hellang.Middleware.ProblemDetails.StatusCodeProblemDetails'.
System.InvalidOperationException: Hellang.Middleware.ProblemDetails.StatusCodeProblemDetails cannot be serialized because it does not have a parameterless constructor.
   at System.Xml.Serialization.TypeDesc.CheckSupported()
   at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError)
   at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.CreateSerializer(Type type)

Looks like StatusCodeProblemDetails would need to provide a default constructor that calls the base ProblemDetails constructor.  Is this something that can be supported?

**Comment by khellang** [comment]
> Looks like StatusCodeProblemDetails would need to provide a default constructor that calls the base ProblemDetails constructor. Is this something that can be supported?

Sure, I'll accept a PR for this, preferably with a test or two. I'd like to make it `private`/`internal` though; status code problem details without an actual status code doesn't make much sense, and should only be allowed to be called by a serializer.

**Comment by janRucka** [comment]
I wanted to create exactly the same issue. I created commit with failing tests which demonstate it:
https://github.com/janRucka/Middleware/commit/7be9b48f1a5a4b639d2c80a6b5d7858043d32e8e

**Comment by khellang** [comment]
In 5.0.0, the middleware no longer uses `StatusCodeProblemDetails` (it uses `StatusCodeProblemDetails.Create`, which returns a vanilla MVC `ProblemDetails` instance with the same information). This should probably make this issue a bit better.

**Comment by khellang** [comment]
I will close this issue as the middleware itself no longer creates instances of custom `ProblemDetails` sub-types.
